dvsa/olcs-selfserve

module/Application/src/Controller/UndertakingsController.php, module/Olcs/src/Table/Tables/correspondence.table.php
Refactors the previously defined constants into static variables provided by `olcs-common` package.
=> fix: refactor date constants to static variables

composer.json, composer.lock
Switch composer OLCS packages to dev-project/messages
=> feat: OLCS composer packages to dev-project/messaging

module/Olcs/src/Form/Model/Form/Surrender/Fieldset/CommunityLicenceStolen.php
Fixes form annotations to fix surrendering of community licences
Related issue: [VOL-4876](https://dvsa.atlassian.net/browse/VOL-4876)
=> fix: stolen community licence journey now completes

module/Olcs/src/Controller/Initializer/Navigation.php, module/Olcs/src/Controller/Listener/NavigationFactory.php, module/Olcs/src/Navigation/DashboardNavigationFactory.php, test/Olcs/src/Controller/Initializer/NavigationTest.php, test/Olcs/src/Controller/Listener/NavigationTest.php, test/Olcs/src/FormService/Form/Lva/PsvVehiclesVehicleTest.php, test/Olcs/src/Mvc/CookieBannerListenerTest.php, test/Olcs/src/Navigation/DashboardNavigationFactoryTest.php
Unit test fixes and improvements
Related issue: [VOL-4713](https://dvsa.atlassian.net/browse/VOL-4713)
=> fix: Navigation unit test

module/Olcs/config/module.config.php, module/Olcs/src/Controller/ConversationsController.php, module/Olcs/view/messages-new.phtml, module/Olcs/view/messages-view.phtml, module/Olcs/view/partials/conversations-right-column.phtml
Add the ability to start a new conversation.
This feature needs to hide behind a feature toggle until it is needed.
Related issue: [VOL-4912](https://dvsa.atlassian.net/browse/VOL-4912)
=> feat: Start conversation link

module/Olcs/view/partials/conversations-right-column.phtml
Sidebar header
Related issue: [VOL-4912](https://dvsa.atlassian.net/browse/VOL-4912)
=> feat: Add header to new sidebar for start link

test/Olcs/src/Controller/Auth/LoginControllerFactoryTest.php, test/Olcs/src/Controller/Auth/LoginControllerTest.php, test/Olcs/src/Controller/Licence/Vehicle/ListVehicleControllerTest.php, test/Olcs/src/Controller/Licence/Vehicle/SwitchBoardControllerTest.php, test/Olcs/src/Controller/SessionTimeoutControllerTest.php
Refactored tests by removing dependency and duplication of serviceManager
Related issue: [JIRA_TICKET_NUMBER](LINK_TO_JIRA_TICKET)
=> test(refactored): remove servicemanager

composer.lock, module/Olcs/src/Controller/ConversationsController.php, module/Olcs/src/Controller/Factory/ConversationsControllerFactory.php, module/Olcs/src/Form/Model/Fieldset/Message/Reply.php, module/Olcs/src/Form/Model/Form/Message/Reply.php, module/Olcs/view/messages-view.phtml, test/Olcs/src/Controller/ConversationsControllerTest.php
Enable/disable file upload for messaging with upload functionality.
Related issue: [VOL-4393](https://dvsa.atlassian.net/browse/VOL-4393)
=> feat: Enable/Disable Messaging File Upload

module/Olcs/src/Form/Model/Fieldset/Message/Reply.php, module/Olcs/src/Form/Model/Form/Message/Create.php
Turn off HTML form validation for create (use Common/Form)
Fix validation info on Reply
Related issue: [VOL-5003](https://dvsa.atlassian.net/browse/VOL-5003)
=> fix: use common form for Create; Fix validation message

composer.lock, module/Olcs/src/Controller/ConversationsController.php, module/Olcs/src/Table/Tables/messages-view.table.php, module/Olcs/view/messages-view.phtml, test/Olcs/src/Controller/ConversationsControllerTest.php
Show conversation title on conversation page.
Related issue: [VOL-5031](https://dvsa.atlassian.net/browse/VOL-5031)
=> feat: Conversation subject title on message list

module/Olcs/src/Controller/ConversationsController.php
Use other docs for message file uploads.
=> chore: Change upload location for message files

composer.lock
bump common and utils packages
=> chore: bump common and utils packages

.gitignore, composer.json, composer.lock, config/application.config.php, config/autoload/.gitignore, config/autoload/config-parameter.global.php, config/autoload/config.global.php, config/autoload/local.php.dist, config/container.php, config/development.config.php.dist, public/govukaccount-redirect.php, public/index.php
Migrate config from Puppet.
Related issue: https://dvsa.atlassian.net/browse/VOL-4492
=> feat: migrate config to application

module/Olcs/src/Controller/ConversationsController.php, module/Olcs/src/Form/Model/Fieldset/Message/Actions.php, module/Olcs/src/Form/Model/Fieldset/Message/Create.php, module/Olcs/src/Form/Model/Fieldset/Message/CreateInput.php, module/Olcs/src/Form/Model/Fieldset/Message/Reply.php, module/Olcs/src/Form/Model/Fieldset/Message/ReplyInput.php, test/Olcs/src/Controller/ConversationsControllerTest.php
Move file uploader above the send button
Related issue: [VOL-5120](https://dvsa.atlassian.net/browse/VOL-5120)
=> feat: Move file uploader above the send button

composer.lock
=> chore: bump olcs-common to 6.7.6

composer.lock
Bump olcs-transfer dep to 6.8.0
=> chore: Bump olcs-transfer dependency to 6.8.0

module/Olcs/src/Controller/Lva/AbstractUploadEvidenceController.php
Prevent previously uploaded files from being deleted.
Related issue: [VOL-3200](https://dvsa.atlassian.net/browse/VOL-3200)
=> fix: Prevent previously uploaded evidence from being deleted

composer.lock
Bump olcs-common to 7.0.3
Related issue: [VOL-3003](https://dvsa.atlassian.net/browse/VOL-3003)
=> chore: olcs-common version bump (7.0.3)

composer.json, composer.lock
Common version bump to bring in content change ticket
=> chore: bump olcs-common minimum required version

composer.json, module/Olcs/src/Controller/FeesController.php
Reverts dvsa/olcs-selfserve#137
=> chore: revert "fix: Only show valid fees for licences"

config/autoload/config.global.php
=> feat: add CDN support

composer.json, composer.lock
=> fix: bump olcs-common minimum required version

config/autoload/config.global.php
As title.
Context is that we're logging a lot of information at the moment and missing vital parts.
=> feat: change log level to `WARN`

composer.json, composer.lock
Upgrade min olcs-common version
=> feat: Upgrade olcs-common dependency to ^7.6.0

module/Application/src/View/Model/ApplicationOverviewSection.php, module/Application/test/View/Model/ApplicationOverviewSectionTest.php
Fix application status tag cases.
Related issue: [VOL-5668](https://dvsa.atlassian.net/browse/VOL-5668)
=> fix: Fix application status tag cases.
