phpunit.xml.dist

set memory_limit to 4G in PHPunit configuration
Related issue: [JIRA_TICKET_NUMBER](LINK_TO_JIRA_TICKET)

chore(config): set memory_limit to 4G in PHPunit configuration

---

module/Olcs/src/Controller/ConversationsController.php
module/Olcs/src/Table/Tables/messages-view.table.php
module/Olcs/view/messages-view.phtml
test/Olcs/src/Controller/ConversationsControllerTest.php

Case worker can select a conversation, they are then taken to a page where they can view the messages related to that conversation.
Related issue: [VOL-4805](https://dvsa.atlassian.net/browse/VOL-4805)

feat: List messages in a conversation.

---

module/Olcs/src/Controller/Factory/Search/SearchControllerFactory.php
module/Olcs/src/Form/Element/SearchDateRangeFieldsetFactory.php
module/Olcs/src/Form/Element/SearchFilterFieldsetFactory.php
module/Olcs/src/Form/Element/SearchOrderFieldsetFactory.php
module/Olcs/src/Form/Model/Form/SimpleSearch.php
module/Olcs/src/Form/Model/Form/TransportManagerApplicationResend.php
module/Olcs/view/layouts/main-search-results.phtml
module/Olcs/view/olcs/user-forgot-username/check-email.phtml
module/Olcs/view/olcs/user-registration/check-email.phtml
module/Olcs/view/pages/fees/late.phtml
module/Olcs/view/search/bus-browse-results.phtml

Fixes for Logged in / Logged out self-serve search. Some fixes to other view files that had same issue too.
Related issue: [VOL-4862](https://dvsa.atlassian.net/browse/VOL-4862)

fix: resolve search issues

---

module/Olcs/view/olcs/user-forgot-username/check-email.phtml
module/Olcs/view/olcs/user-registration/check-email.phtml
module/Olcs/view/pages/lva-details.phtml

Several fixes for broken view helper calls in template files
Related issue: [VOL-4865](https://dvsa.atlassian.net/browse/VOL-4865)

fix: Resolve several templates incorrect use of view Helpers

---

composer.lock

Bump `olcs/olcs-common` to `5.0.0-beta.2`

chore: bump `olcs/olcs-common` to `5.0.0-beta.2`

---

composer.lock

Bump `olcs/olcs-transfer` to `5.0.0-beta.8`.

chore: bump `olcs/olcs-transfer` to `5.0.0-beta.8`

---

module/Olcs/view/olcs/user-forgot-username/check-email.phtml
module/Olcs/view/olcs/user-registration/check-email.phtml
module/Olcs/view/pages/lva-details.phtml

Calls url helper method properly in 2 refactored templates.
Related issue: [VOL-4874](https://dvsa.atlassian.net/browse/VOL-4874)

fix: Fix url helper calls in 2 templates

---

composer.json
composer.lock

Laminas Form had an [issue](https://github.com/laminas/laminas-form/commit/733ea7eda2689147a6b2f7ad86d00133eea1f421) that was resolved only in v3.9.0 onwards. We use Laminas Form v3.4.x due to PHP version constraints. The fork that this now points to simply cherry-picks that commit until a point we can point back to the latest Laminas form version (PHP upgrade epic).
Related issue: https://dvsa.atlassian.net/browse/VOL-4871

fix: replace `laminas-form` with patched fork

---

composer.lock

Bump `olcs-common` to `5.0.0-beta.4`

chore: bump `olcs-common` to `5.0.0-beta.4`

---

composer.lock
module/Olcs/src/Table/Tables/messages.table.php

External message list should be split in to two columns with status in the right column.
Related issue: [VOL-4805](https://dvsa.atlassian.net/browse/VOL-4805)

feat: Message list split in to two columns

---

composer.lock

Bump `olcs-common` to `5.0.0-beta.6`

chore: bump `olcs-common` to `5.0.0-beta.6`

---

module/Olcs/config/module.config.php
module/Olcs/src/Controller/Factory/Search/SearchControllerFactory.php

The projects were using a mix of `Navigation` and `navigation` resulting in two different objects - this caused issues with navigation as two different objects were being mutated and used.
I went with `navigation` even though it was a larger refactor due to that being the alias that is registered in the upstream package: https://github.com/laminas/laminas-navigation/blob/2f39ab2f929d23da89bbb4401efdccb6e72eaf68/src/ConfigProvider.php#L33.
Related issue:  https://dvsa.atlassian.net/browse/VOL-4900 & https://dvsa.atlassian.net/browse/VOL-4915

fix: consolidate `Navigation` and `navigation`

---

module/Olcs/src/Table/Tables/txc-inbox.table.php

Replace formatter string name with proper class and use stmt.
Related issue: [4926](https://dvsa.atlassian.net/browse/VOL-4926)

fix: Old string formatter name to FQCN and Import.

---

module/Olcs/src/Table/Tables/txc-inbox.table.php
module/Olcs/view/olcs/ebsr/uploads/detail.phtml

Two issues: 
- invalid reference to unknown constant.
- view path changed to relative path instead of the incorrect absolute route.
Related issue: https://dvsa.atlassian.net/browse/VOL-4904

fix: fix error on EBSR pages

---

module/Olcs/src/Controller/DashboardController.php

Improve TOPS Report Error handling
Related issue: [VOL-4969](https://dvsa.atlassian.net/browse/VOL-4969)

fix: improve TOPS report error handling

---

module/Olcs/src/Controller/Listener/Navigation.php
test/Olcs/src/Controller/Listener/NavigationTest.php

Changes rule to not show messaging tab on selfserve when messaging is disabled.
Related issue: [VOL-4713](https://dvsa.atlassian.net/browse/VOL-4713)
Specifically, AC5 and the comment relating to it.
See also: [VOL-4920](https://dvsa.atlassian.net/browse/VOL-4920)

Add "Messaging not disabled" to tab display conditions

---

module/Olcs/src/Controller/Listener/Navigation.php

Navigation.php throwing a notice due to array key not always existing.

fix: Trying to access array key on null in navigation

---

module/Olcs/src/Form/Model/Fieldset/Message/Create.php
module/Olcs/src/Form/Model/Fieldset/Message/Reply.php

Update to new form annotation style

chore: form annotation changes

---

composer.lock
module/Olcs/config/module.config.php
module/Olcs/src/Controller/ConversationsController.php
module/Olcs/src/Controller/Factory/ConversationsControllerFactory.php
module/Olcs/src/Controller/Listener/Navigation.php
module/Olcs/src/Service/Data/MessagingAppOrLicNo.php
module/Olcs/view/partials/tabs-nav.phtml
phpunit.xml.dist
test/Olcs/src/Controller/ConversationsControllerTest.php
test/Olcs/src/Controller/Listener/NavigationTest.php

Queries the unread messages in DashboardController and add as variable to navigation menu
Related issue: [VOL-4339](https://dvsa.atlassian.net/browse/VOL-4339)

feat: Unread counter on Messages tab

---

module/Olcs/src/Controller/ConversationsController.php
module/Olcs/view/messages-new.phtml
module/Olcs/view/messages-view.phtml
test/Olcs/src/Controller/ConversationsControllerTest.php

Add links to get back to conversation list
Related issue: [VOL-5048](https://dvsa.atlassian.net/browse/VOL-5048)

feat: Back to conversations links

---

composer.lock
module/Olcs/src/FormService/Form/Lva/AbstractLvaFormServiceFactory.php
module/Olcs/src/FormService/Form/Lva/TypeOfLicence/ApplicationTypeOfLicence.php
test/Olcs/src/FormService/Form/Lva/TypeOfLicence/ApplicationTypeOfLicenceTest.php

Due to the changes to internal permissions code, this controller in selfserve also needs updating (shared abstracts)
Related issue: [VOL-5103](https://dvsa.atlassian.net/browse/VOL-5103)

fix: VOL-5103 update selfserve type of licence controller as it shares the updated controller from common

---

module/Olcs/src/Controller/ConversationsController.php
test/Olcs/src/Controller/ConversationsControllerTest.php

If uploads for messaging is disabled, hide the button on reply.
Related issue: [VOL-4393](https://dvsa.atlassian.net/browse/VOL-4393)

fix: Hide file upload if uploads disabled.

---

module/Permits/src/Permits/Data/Mapper/MapperManager.php

Tidy up laminas 2.5 compatibility code
Related issue: [VOL-3761](https://dvsa.atlassian.net/browse/VOL-3761)

chore: Tidy up laminas 2 3 compatability vol 3761

---

composer.lock
module/Olcs/src/Table/Tables/users.table.php

Use the new `isSelf` method to determine if the user has permission to see resources that are restricted to themselves.
Related issue: https://dvsa.atlassian.net/browse/VOL-5103

fix: fix manage user journey

---

public/govukaccount-redirect.php

Cache directory is relative. This works as `public/index.php` switches the current working directory on each request. `govukaccount-redirect` doesn't go through the `public/index.php`. This PR adds the same `chdir` instruction to this entrypoint.
Related issue: Regression from https://dvsa.atlassian.net/browse/VOL-4492.

fix: add `chdir` to `govukaccount-redirect` to pickup correct cache dir

---

module/Olcs/src/Controller/ConversationsController.php
module/Olcs/src/Form/Model/Fieldset/Message/Create.php
module/Olcs/src/Form/Model/Form/Message/Create.php
test/Olcs/src/Controller/ConversationsControllerTest.php

Allow uploads when starting a new conversation.
Related issue: [VOL-5120](https://dvsa.atlassian.net/browse/VOL-5120)

feat: Allow uploads on a new conversation

---

module/Olcs/src/Controller/Licence/Surrender/StartController.php

Not able to surrender a psv licence, page error.
Related issue: [VOL-5210](https://dvsa.atlassian.net/browse/VOL-5210)

fix: Not able to surrender a psv licence

---

module/Olcs/src/Controller/Lva/Traits/TransportManagerApplicationTrait.php
module/Olcs/src/Controller/Lva/TransportManager/AbstractDeclarationController.php
module/Olcs/src/Controller/Lva/TransportManager/CheckAnswersController.php

Transport Manager journey breaks when TM attempts to submit their details
Related issue: [VOL-5207](https://dvsa.atlassian.net/browse/VOL-5207)

fix: Transport manager journey broken due to type.

---

module/Olcs/src/Controller/Lva/TransportManager/ConfirmationController.php

Another controller user the TM trait re-declared the variable.
Related issue: [VOL-5207 ](https://dvsa.atlassian.net/browse/VOL-5207)

fix: Confirmation page declared tma different to trait

---

module/Olcs/src/Controller/Lva/AbstractUploadEvidenceController.php

There is currently a bug in VOL production which is allowing operators to remove documents previously uploaded as part of a new or variation application, after the application is submitted and status is ‘under consideration’.
Related issue: [VOL-3200](https://dvsa.atlassian.net/browse/VOL-3200)

fix: Don't allow deleting pre submission file uploads

---

module/Olcs/src/Table/Tables/users.table.php

Bug meant it wasn't possible for admin users to remove selfservice users for their organisation, this fixes it.
Requires bump of olcs-common after this PR merged:
https://github.com/dvsa/olcs-common/pull/98
Related issue: [VOL-5243](https://dvsa.atlassian.net/browse/VOL-5243)

fix: VOL-5243 remove buttons now showing correctly on the manage users page

---

composer.json
module/Olcs/src/Controller/FeesController.php

Only show fees for submitted applications.
Related issue: [VOL-233](https://dvsa.atlassian.net/browse/VOL-233)

fix: Only show valid fees for licences

---

config/autoload/config.global.php
config/autoload/local.php.dist

Check the environment variables for an `APP_VERSION`. This is how the application will get it's version once migrated to ECS.

feat: check version in environment variable

---

composer.json
composer.lock

Removed the dependence on our Laminas Form fork. The only practical difference from this is a bump from 3.19.1 to 3.19.2
Related issue: [VOL-5402](https://dvsa.atlassian.net/browse/VOL-5402)

chore: VOL-5402 remove reliance on forked laminas-form package bump to 3.19.2

---

module/Olcs/src/Controller/Licence/Vehicle/RemoveVehicleController.php
module/Olcs/src/Controller/Licence/Vehicle/Reprint/ReprintLicenceVehicleDiscController.php
module/Olcs/src/Controller/Licence/Vehicle/TransferVehicleController.php

Fixes the error when passing an object to `array_key_exists`. This was deprecated in PHP 7.4 and removed in PHP 8.0.
Related issue: https://dvsa.atlassian.net/browse/VOL-5463

fix: resolve `array_key_exists` type error

---

module/Olcs/src/Controller/Licence/Vehicle/TransferVehicleController.php

Tweaks the conditionals so that `null` isn't passed to the `count` call.
Related issue: https://dvsa.atlassian.net/browse/VOL-5465

fix: fix count by `null` in `TransferVehicleController`

---

module/Olcs/src/Controller/Lva/Licence/PeopleController.php

This is not correct and would need fixing through various levels of inheritance.
Fixes:
```
TypeError : Olcs\\Controller\\Lva\\Licence\\PeopleController::deleteAction(): Return value must be of type Laminas\\Http\\Response, Laminas\\View\\Model\\ViewModel returned
```
Related issue: https://dvsa.atlassian.net/browse/VOL-5470

fix: remove return type from `PeopleController::deleteAction`

---

module/Olcs/src/Form/Model/Form/Surrender/CurrentDiscs/Fieldset/InPossessionInfo.php
module/Olcs/src/Form/Model/Form/Surrender/CurrentDiscs/Fieldset/LostInfo.php
module/Olcs/src/Form/Model/Form/Surrender/CurrentDiscs/Fieldset/StolenInfo.php

Related issue: [VOL-5507](https://dvsa.atlassian.net/browse/VOL-5507)

fix: VOL-5507 remove incorrect calls to Laminas number element that was breaking validation

---

composer.lock
module/Olcs/src/Table/Tables/users.table.php

Operator admins no longer see button to remove themselves
selfserve users don't now have a button to remove themselves
Related issue: [VOL-5530](https://dvsa.atlassian.net/browse/VOL-5530)

fix: operator admins no longer see button to remove themselves

---

module/Olcs/view/layouts/base.phtml

Upgrade govuk-frontend to 5.x - requires loading new JS separately.
Related issue: [VOL-4716](https://dvsa.atlassian.net/browse/VOL-4716)

feat: Upgrade govuk frontend

---

module/Olcs/view/layouts/base.phtml

Stop rendering empty nav menu on signin page header
Related issue: [VOL-5680](https://dvsa.atlassian.net/browse/VOL-5680)

fix: Stop rendering empty menu on signin page.
